# unbind C-b
# set-option -g prefix C-Space
# bind C-Space send-prefix
# Alt-Space
if-shell -b '[ "$(echo "$TERM_PROGRAM == Apple_Terminal" | bc)" = 1 ]' {
  set -g terminal-overrides "screen-256color"
}
set-option -sg escape-time 0 # Faster command sequences
# set -sg repeat-time 300 # Increase repeat timeout for resizing
# set -s focus-events on # Detect when the terminal window gains or loses focus (xkbswitch.nvim)
# set -g display-panes-time 800 # Slightly longer pane indicators display time
# set -g display-time 1000 # slightly longer status messages display time
set -g monitor-activity on
set -g visual-activity off
set -g set-clipboard external
set -g mouse on

bind-key a set -g mouse\; display-message "mouse is now #{?mouse,on,off}"
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded"
bind e new-window -n ".tmux.conf" sh -c "vim ~/.tmux.conf"
bind -r l select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r h select-pane -R
bind N previous-window # Select previous window (n select next window)
bind Tab last-window   # Move to last active window
# Swap window left/right keeping current window focused
bind-key -r < swap-window -t - -d
bind-key -r > swap-window -t + -d
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r m resize-pane -Z

# Copy mode
# +-------------------+---------------+
# | Action            | vi            |
# +-------------------+---------------+
# | search            | /             |
# | start selection   | Space         |
# | copy selection    | Enter         |
# | clear selection   | Escape        |
# | exit copy mode    | q             |
# +-------------------+---------------+
set-window-option -g mode-keys vi
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-no-clear

set-option -gq window-status-current-format "#[fg=green,bg=black] #I:#W#F "
set-option -gq window-status-activity-style "bg=green,fg=black,bold,italics"
set-option -gq status-right "%a %-d %b %H:%M "
